POST http://localhost:3000/register
Content-Type: application/json

{
    "name":"sabrina",
    "email":"sabrina@mail.com",
    "password":"password123"
}

### 
POST http://localhost:3000/login
Content-Type: application/json

{
    "email":"sabrina@mail.com",
    "password":"password123"
}

###
GET http://localhost:3000/whoami
Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6InNhYnJpbmEiLCJlbWFpbCI6InNhYnJpbmFAbWFpbC5jb20iLCJpYXQiOjE2ODQxNTYxNzR9.vsDHX-CpmIs71TSpYgK_xzKiFlfeCT13sO0plAx1qjQ